# Generated by Django 4.1.1 on 2022-09-12 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
