# Generated by Django 4.1.1 on 2022-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/default.png', upload_to='user_img', verbose_name='images'),
        ),
    ]
